# Generated by Django 2.1.3 on 2018-11-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=None, max_length=50)),
                ('points', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('year', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('department', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('event_1', models.CharField(max_length=50, null=True)),
                ('event_2', models.CharField(max_length=50, null=True)),
                ('event_3', models.CharField(max_length=50, null=True)),
                ('event_4', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default=None, max_length=50)),
                ('first_prize', models.CharField(default=None, max_length=50)),
                ('second_prize', models.CharField(default=None, max_length=50)),
                ('third_prize', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
