# Generated by Django 2.1.3 on 2018-11-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='event_1',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='event_2',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='event_3',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='event_4',
        ),
        migrations.AddField(
            model_name='registration',
            name='events',
            field=models.CharField(choices=[('kadaprasangham', 'KADHAPRASANGAM'), ('monoact', 'MONOACT'), ('western_solo', 'WESTERN SOLO'), ('mappila', 'MAPPILAPATTU'), ('mimicry', 'MIMICRY'), ('naadoodinritham', 'NAADODINIRTHAM'), ('ottamthulla', 'OTTANTHULLAL'), ('bharathanatyam', 'BHARATHANATYAM'), ('mohiniyattam', 'MOHINIYATTAM'), ('speech_eng', 'SPEECH ENGLISH'), ('speech_mal', 'SPEECH MALAYALAM'), ('speech_hin', 'SPEECH HINDI'), ('violin', 'VIOLIN'), ('veena', 'VEENA'), ('organ', 'ORGAN'), ('thabala', 'THABALA'), ('guitar', 'GUITAR'), ('mrithangam', 'MRITHANGAM'), ('kavitha_mal', 'KAVITHA MALAYALAM'), ('poem_eng', 'POEM ENGLISH'), ('poem_hin', 'POEM HINDI'), ('poem_arab', 'POEM ARABIC'), ('poem_sanskrit', 'POEM SANSKRIT'), ('lightmusic', 'LIGHT MUSIC'), ('classic_music', 'CLASSICAL MUSIC')], default='KADHAPRASANGAM', max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
