# Generated by Django 2.1.3 on 2018-11-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0003_auto_20181116_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
