# Generated by Django 2.1.3 on 2018-11-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0011_auto_20181118_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('Mtech', 'M.Tech')], default='2', max_length=10),
        ),
    ]
