# Generated by Django 2.1.3 on 2018-11-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0012_auto_20181118_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='first_prize',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='result',
            name='second_prize',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='result',
            name='third_prize',
            field=models.TextField(default=None),
        ),
    ]
