# Generated by Django 2.1.3 on 2020-02-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0013_auto_20181120_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnstageResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default=None, max_length=50)),
                ('first_prize', models.TextField(default=None)),
                ('second_prize', models.TextField(default=None)),
                ('third_prize', models.TextField(default=None)),
            ],
        ),
        migrations.RenameModel(
            old_name='Result',
            new_name='OffstageResult',
        ),
    ]
