# Generated by Django 2.1.3 on 2018-11-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='point',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rank',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
